### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CommandCracker8** [Demeng7215/PluginBase#10]
Hiya. When starting my plugin that uses PluginBase, I get this error:
```
[17:16:22] [Server thread/ERROR]: Error occurred while enabling PluginBaseTestSubCMD v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: LOCALE
        at dev.demeng.pluginbase.internal.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:117) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:449) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:100) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:168) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2722) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:168) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at dev.demeng.pluginbase.internal.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        at dev.demeng.pluginbase.plugin.BasePlugin.onEnable(BasePlugin.java:64) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:877) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.Bukkit.reload(Bukkit.java:675) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:745) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:475) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:439) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[Spigot%201.17.1.jar:3178-Spigot-eac3cd9-a6292cc]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
@Demeng7215 what should I do to fix this?

**Comment by demengc** [comment]
Should have been fixed in the latest version

**Comment by CommandCracker8** [comment]
I'm using the latest version

**Comment by CommandCracker8** [comment]
Do you know how I can fix it?

**Comment by CommandCracker8** [comment]
@Demeng7215

**Comment by demengc** [comment]
I’ll try to make time to check this out tonight.

**Comment by CommandCracker8** [comment]
Thanks!

**Comment by demengc** [comment]
Fixed

**Comment by CommandCracker8** [comment]
Thanks, I'll check it tomorrow.

**Comment by CommandCracker8** [comment]
It works! Thank!
