### ISSUE TITLE
Error with disabling plugin

### ISSUE THREAD

**Issue by CommandCracker8** [Demeng7215/PluginBase#5]
When the plugin disables this error occures:
```
java.lang.NoClassDefFoundError: dev/demeng/pluginbase/ServerProperties
        at dev.demeng.pluginbase.plugin.BasePlugin.onDisable(BasePlugin.java:98) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:588) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:915) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.Bukkit.reload(Bukkit.java:769) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-104]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-104]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.demeng.pluginbase.ServerProperties
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-104]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-104]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 18 more
```

**Comment by demengc** [comment]
Still an issue with your project setup or how you're compiling the library. The ServerProperties class does exist: https://github.com/Demeng7215/PluginBase/blob/master/pluginbase-core/src/main/java/dev/demeng/pluginbase/ServerProperties.java

**Comment by CommandCracker8** [comment]
Well I'm now using Jitpack and that's not with building it. I can see in my project that it's there...

**Comment by CommandCracker8** [comment]
Turns out you still need to add the maven dependencies of PluginBase to the maven even though it's imported with Jitpack, oof.

**Comment by CommandCracker8** [comment]
Welp imma close this now :D
